---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat" and
      ansible_distribution_major_version | int >= 7

- name: Install graphite-api RPM package
  yum:
    name: "{{ graphite_api_influxdb_pkg }}"
  notify:
    - Restart graphite-api service
