---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat" and
      ansible_distribution_major_version | int >= 7

- name: Install graphite-api RPM package and dependencies
  yum:
    name: "{{ item }}"
  with_items: "{{
    [ graphite_api_influxdb_pkg ] +
    graphite_api_influxdb_pkg_deps }}"
  notify:
    - Restart graphite-api service
  tags:
    - graphite_api_influxdb_pkg
